apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
spec:
  containers:
  - name: app
    image: busybox:latest
    command: ["sh", "-c", "echo 'Dynamic provision test' > /data/dynamic.txt; sleep 3600"]
    volumeMounts:
    - name: workdir
      mountPath: /data
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: dynamic-pvc
  restartPolicy: Never
