apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-pod
spec:
  containers:
  - name: writer
    image: busybox:latest
    command: ["sh", "-c", "date > /data/message.txt; sleep 3600"]
    volumeMounts:
    - name: cache-volume
      mountPath: /data
  volumes:
  - name: cache-volume
    emptyDir: {}
  restartPolicy: Never
