apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: busybox:latest
    command: ["sh", "-c", "echo '--- ENV VAR ---'; echo $DB_USER; echo '--- MOUNTED FILE ---'; cat /etc/db-credentials/DB_PASSWORD; sleep 3600"]
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_USER
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/db-credentials
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: db-credentials
  restartPolicy: Never
