name: Conditionals Pipeline

on: [push, pull_request]

jobs:
  flow-control:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Run on Main
        if: github.ref == 'refs/heads/main'
        run: echo "Only on main branch"

      - name: Risky Step
        id: risky
        continue-on-error: true
        run: exit 1

      - name: Run if previous failed
        if: failure() && steps.risky.conclusion == 'failure'
        run: echo "Previous step failed, but continue-on-error: true allowed execution"
