name: Secrets Test Pipeline

on: [push]

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret is set
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: Use secret as environment variable
        env:
          SEC_MSG: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "Using secret securely via env var (length of message): ${#SEC_MSG}"
